config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :attendances
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	after_create :attendance_send

	belongs_to :user
	belongs_to :event

	# Each time someone participates to an event, organizer receives a recap email via
	# this method
	def attendance_send
		AttendanceMailer.participation_email(self.user, self.event.organizer, self.event).deliver_now
	end

end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :organizer, class_name: "User"

	validates :start_date, presence: true 
	validate :is_start_date_past?

	validates :duration, presence: true
	validate :is_duration_correct?

	validates :title, presence: true, length: {minimum: 5, maximum: 140}
	validates :description, presence: true, length: {minimum: 20, maximum: 1000}

	validates :price, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 1000}
	validates :location, presence: true

	# To check if the date is correct
	def is_start_date_past?
		if start_date < Time.now
			errors.add(:start_date, "can't be in the past")
		end
	end

	# To check if the duration is correct
	def is_duration_correct?
		if duration <= 0 || (duration % 5) != 0 
			errors.add(:duration, "must be positive and a multiple of 5, easy !")
		end			
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
after_create :welcome_send

    has_many :attendances
	has_many :events, through: :attendances
    has_many :organizers, foreign_key: "organizer_id", class_name: "Event"
    
    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:stripe_customer_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :encrypted_password, :description, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stripe_customer_id %>
    <%= form.text_field :stripe_customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Stripe customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.stripe_customer_id %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stripe customer:</strong>
  <%= @attendance.stripe_customer_id %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <%= image_tag("avataaars.svg", class: "masthead-avatar mb-5" ) %>
                <<!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0"> Eventbrite</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">You can't miss it !</p>
            </div>
        </header>

<p id="notice"><%= notice %></p>

                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Events</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>

<div class="container d-flex align-items-center flex-column">
                    <p>
                    <%= button_to 'New Event', new_event_path , class:"btn btn-danger btn-lg" %>
                    </p>
</div>
                <!-- Portfolio Grid Items-->
                <div class="row">
                    <!-- Portfolio Item 1-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal1">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <%= image_tag("cabin.png", class: "img-fluid" ) %>
                        </div>
                    </div>
                    <!-- Portfolio Item 2-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal2">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <%= image_tag("cake.png", class: "img-fluid" ) %>
                        </div>
                    </div>
                    <!-- Portfolio Item 3-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal3">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <%= image_tag("circus.png", class: "img-fluid" ) %>
                        </div>
                    </div>
                    <!-- Portfolio Item 4-->
                    <div class="col-md-6 col-lg-4 mb-5 mb-lg-0">
                        <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal4">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <%= image_tag("game.png", class: "img-fluid" ) %>
                        </div>
                    </div>
                    <!-- Portfolio Item 5-->
                    <div class="col-md-6 col-lg-4 mb-5 mb-md-0">
                        <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal5">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <%= image_tag("safe.png", class: "img-fluid" ) %>
                        </div>
                    </div>
                    <!-- Portfolio Item 6-->
                    <div class="col-md-6 col-lg-4">
                        <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal6">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                      <%= image_tag("submarine.png", class: "img-fluid" ) %>                     
                         </div>
                    </div>
                </div>
            </div>
        </section>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>Duration</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.start_date %></td>
        <td><%= event.duration %></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.price %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= button_to 'New Event', new_event_path, class:"btn btn-danger btn-lg" %>

app/views/events/new.html.erb
        <section class="page-section" id="contact">
            <div class="container">
                <!-- Contact Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Create an Event</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>

<!-- Form zone-->
<div class="container col-6">

	<!-- Form to create a new event  -->
	<%= form_tag events_path, multipart: true do %>

	<%= label_tag 'Title' %>
	<%= text_field_tag 'title', @event.title, placeholder: "Your title", class: "form-control mb-3" %>

	<%= label_tag 'Start date' %>
	<%= text_field_tag 'start_date', @event.start_date, placeholder: "Exemple: 2020/06/12 12:00:00", class: "form-control mb-4" %>

	<%= label_tag 'Duration' %>
	<%= text_field_tag 'duration', @event.duration, placeholder: "Duration must be a multiple of 5", class: "form-control mb-4" %>

	<%= label_tag 'Description' %>
	<%= text_area_tag 'description', @event.description, placeholder: "A short description of your event", class: "form-control mb-4" %>

	<%= label_tag 'Price' %>
	<%= text_field_tag 'price', @event.price, placeholder: "Price in euros (without the € sign)", class: "form-control mb-4" %>

	<%= label_tag 'Location' %>
	<%= text_field_tag 'location', @event.location, placeholder: "Address of the event", class: "form-control mb-4" %>

	<%= label_tag 'Event picture' %>
	<%= file_field_tag :eventpictures %>

	<br/><br/>


	<%= submit_tag "Create event", class: "btn btn-primary" %>

	<% end %>

	<!-- Showing possible events -->
	<% if @event.errors.any? %>

	<div class="alert alert-danger alert-dismissible fade show m-4" role="alert">
		<p><strong>We couldn't create the event for the following reason(s) :</strong></p>
		<ul>
			<% @event.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<% end %>
		</ul>
	</div>

	<% end %>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
 

<div class="container">
	<div class="row text-center justify-content-center mt-3">
		<!-- Event title -->
		<h3 class="col-12"><%="#{@event.title}" %></h3>
<p class="col-12">
			<small class="text-muted">Description</small><br/>
			<%= @event.description %>
		</p>

		<!-- Number of attendees -->
		<p class="col-12">
			<small class="text-muted">Number of attendees</small><br/>
			<%= @event.users.count %>
		</p>
		
		<!-- Organizer email -->
		<p class="col-12">
			<small class="text-muted">Organizer</small><br/>
			<%= @event.organizer.email %>
		</p>
		
		<!-- Start date -->
		<p class="col-12">
			<small class="text-muted">Start date</small><br/>
			<%= @event.start_date %>
		</p>
		
		<!-- Event location -->
		<p class="col-12">
			<small class="text-muted">Location</small><br/>
			<%= @event.location %>
		</p>

		<!-- Event price -->
		<p class="col-12">
			<small class="text-muted">Price</small><br/>
			<%= "#{@event.price} €" %>
		</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
         <title>Eventbrite</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="<%= events_path %>">Eventbrite</a><button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu <i class="fas fa-bars"></i></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<%= new_event_path %>">New Event</a></li>
                    </ul>
                    <ul>
                    <div class="dropdown">
                  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    Profile
                  </button>
                  <% if user_signed_in? %>
                 <!-- Dropdown when logged in -->
                    <li class="nav-item dropdown">
              <div class="dropdown-menu">
              <%= link_to "My profile", user_path(current_user.id), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path , method: 'delete', class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
          <!-- Dropdown when logged out -->
          <li class="nav-item dropdown">
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
            </div>
           </li>
          <% end %>
        </ul>
       </div>
     </div>
  </nav>

    <%= yield %>

         <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="assets/mail/jqBootstrapValidation.js"></script>
        <script src="assets/mail/contact_me.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :encrypted_password %>
    <%= form.text_field :encrypted_password %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Description</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.description %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">
	<div class="row text-center justify-content-center mt-3">
		<!-- User's name -->
		<h3 class="col-12"><%="#{@user.first_name}" %> <%="#{@user.last_name}"%></h3>

		<!-- Description -->
		<p class="col-12">
			<small class="text-muted">Description</small><br/>
			<%= @user.description %>
		</p>
		<!-- Email -->
		<p class="col-12">
			<small class="text-muted">Email</small><br/>
			<%= @user.email %>
		</p>
		<%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-primary mb-4' %>
	</div>

	<!-- User's events -->
	<div class="row justify-content-center">	
		<% @user_events.each do |event| %>
		<div class="col-md-4 mt-3">
			<div class="card mb-3">
				<div class="card-body">
					<h5 class="card-title"><%= event.title %></h5>
					<p class="card-subtitle mb-2 text-muted"><small><%= event.location %></small></p>
					<p class="card-text"><%= event.price %> €</p>
					<%= link_to "See more",  event_path(event.id), class:"btn-primary btn-sm" %>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>